### ISSUE TITLE
axioms.md comments

### ISSUE THREAD

**Issue by cogan-shimizu** [CJMenart/MetadataRepresentationProject#1]
#### Formatting 
* I would appreciate following the graphical syntax as can be found [here](https://github.com/kastle-lab/cs7810-intro-to-ke/blob/master/templates/schema-diagram.graphml). It actually looks like your own graphical syntax is inconsistent across your schema diagrams.
* Please put the axioms into inline code fences for readability
* Capitalize all concept/class names, even in the descriptions
* Typically, the module name is the singular case of the concept
* Maneuver is spelled wrong

#### Logic stuff
In general, these look good!
* `Lane/Rules/1` try formatting this into a `if...then` statement.
* in `Lane` module, there is an axiom with a missing description

**Comment by CJMenart** [comment]
Believe these have been addressed by @AMoore86. Except possibly the first? But I cannot find any inconsistencies in the yEd diagrams currently. If I don't hear otherwise, will close this in a couple days.

**Comment by cogan-shimizu** [comment]
They are just picky things re: the schema diagrams.
I tend to use the pastel yellow (rather than the retina searing yellow), the second weight line boldness, and boxes that tightly bound the text. Ultimately what you have is fine, and feel free to close the issue.
